"use client";
import { useEffect, useState } from "react";
import axios from "axios";
import toast from "react-hot-toast";

const API = process.env.NEXT_PUBLIC_IS_PROD === "true" ? "https://localhelp-hu2d.onrender.com" : "http://localhost:4040";
export default function AdminRequestsPage() {
  const [requests, setRequests] = useState([]); const [providers, setProviders] = useState([]); const [loading, setLoading] = useState(true); const [choice, setChoice] = useState({});
  const headers = { Authorization: `Bearer ${typeof window !== "undefined" ? localStorage.getItem("token") : ""}` };
  async function load() { try { const [r, p] = await Promise.all([axios.get(`${API}/api/admin/service-requests`, { headers }), axios.get(`${API}/api/admin/providers`, { headers })]); setRequests(r.data.requests || []); setProviders((p.data.providers || []).filter(x => x.user?.status === "ACTIVE" && x.isAvailable !== false)); } catch (e) { toast.error(e.response?.data?.message || "Could not load operations queue"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function assign(id) { if (!choice[id]) return toast.error("Choose a technician first"); try { await axios.post(`${API}/api/admin/service-requests/${id}/assign`, { technicianId: choice[id] }, { headers }); toast.success("Technician assigned"); load(); } catch (e) { toast.error(e.response?.data?.message || "Assignment failed"); } }
  return <main className="min-h-screen bg-[#F4F5F0] px-4 py-8 text-[#112E40]"><div className="mx-auto max-w-6xl"><a href="/admin/dashboard" className="text-[#127373]">← Admin dashboard</a><h1 className="mt-6 text-3xl font-bold">Service request operations</h1><p className="mt-2 text-gray-600">Review new repair requests and assign available technicians.</p>{loading ? <p className="mt-8 rounded-xl bg-white p-8 text-center">Loading queue…</p> : <div className="mt-8 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-[#112E40] text-white"><tr><th className="p-4">Request</th><th className="p-4">Customer / appliance</th><th className="p-4">Problem</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{requests.map(r => <tr key={r.id} className="border-b last:border-0"><td className="p-4 font-mono text-xs">#{r.id.slice(0, 8)}</td><td className="p-4"><b>{r.customer?.name}</b><br /><span className="text-gray-500">{r.appliance?.brand} {r.appliance?.model || r.appliance?.type}</span></td><td className="max-w-xs p-4">{r.problem}</td><td className="p-4"><span className="rounded-full bg-[#E8F2EE] px-3 py-1 text-xs font-semibold text-[#127373]">{r.status.replaceAll("_", " ")}</span>{r.technician && <p className="mt-2 text-xs">{r.technician.name}</p>}</td><td className="p-4">{r.status === "REQUESTED" ? <div className="flex gap-2"><select value={choice[r.id] || ""} onChange={e => setChoice({ ...choice, [r.id]: e.target.value })} className="rounded-lg border p-2"><option value="">Select technician</option>{providers.map(p => <option key={p.user.id} value={p.user.id}>{p.user.name}</option>)}</select><button onClick={() => assign(r.id)} className="rounded-lg bg-[#127373] px-3 py-2 font-semibold text-white">Assign</button></div> : <span className="text-gray-500">Managed</span>}</td></tr>)}</tbody></table>{requests.length === 0 && <p className="p-10 text-center text-gray-600">No service requests in the queue.</p>}</div>}</div></main>;
}
