"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import axios from "axios";
import toast from "react-hot-toast";
import { FaArrowLeft, FaWrench, FaMapMarkerAlt } from "react-icons/fa";

const API_BASE = process.env.NEXT_PUBLIC_IS_PROD === "true" ? "https://localhelp-hu2d.onrender.com" : "http://localhost:4040";
const nextActions = { ASSIGNED: ["CONFIRMED"], CONFIRMED: ["TECHNICIAN_ON_WAY"], TECHNICIAN_ON_WAY: ["DIAGNOSING"], IN_PROGRESS: ["WAITING_FOR_PARTS", "COMPLETED"], WAITING_FOR_PARTS: ["IN_PROGRESS"] };
const labels = { CONFIRMED: "Accept job", TECHNICIAN_ON_WAY: "On my way", DIAGNOSING: "Start diagnosis", IN_PROGRESS: "Start repair", WAITING_FOR_PARTS: "Waiting for parts", COMPLETED: "Mark completed" };

export default function TechnicianRequestsPage() {
  const router = useRouter(); const [requests, setRequests] = useState([]); const [loading, setLoading] = useState(true); const [diagnosis, setDiagnosis] = useState({});
  const token = typeof window !== "undefined" ? localStorage.getItem("token") : null; const headers = { Authorization: `Bearer ${token}` };
  async function load() { try { const r = await axios.get(`${API_BASE}/api/service-requests`, { headers }); setRequests(r.data.requests || []); } catch (e) { toast.error(e.response?.data?.message || "Could not load assigned jobs"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function changeStatus(id, status, note) { try { await axios.patch(`${API_BASE}/api/service-requests/${id}/status`, { status, note }, { headers }); toast.success(`Request moved to ${status.replaceAll("_", " ")}`); load(); } catch (e) { toast.error(e.response?.data?.message || "Invalid workflow action"); } }
  async function saveDiagnosis(id) { const note = diagnosis[id]?.trim(); if (!note || note.length < 10) return toast.error("Add at least 10 characters of diagnosis"); await changeStatus(id, "IN_PROGRESS", `Diagnosis: ${note}`); setDiagnosis({ ...diagnosis, [id]: "" }); }
  return <main className="min-h-screen bg-[#F4F5F0] px-4 py-8 text-[#112E40]"><div className="mx-auto max-w-5xl"><button onClick={() => router.back()} className="mb-6 flex items-center gap-2 text-[#127373]"><FaArrowLeft /> Back</button><h1 className="text-3xl font-bold">Assigned service requests</h1><p className="mt-2 text-gray-600">Complete only the next valid action in each repair lifecycle.</p>{loading ? <p className="mt-8 rounded-xl bg-white p-8 text-center">Loading jobs…</p> : requests.length === 0 ? <div className="mt-8 rounded-2xl bg-white p-12 text-center"><FaWrench className="mx-auto mb-4 text-4xl text-[#127373]" /><h2 className="text-xl font-bold">No assigned jobs</h2><p className="mt-2 text-gray-600">New assignments from operations will appear here.</p></div> : <div className="mt-8 space-y-5">{requests.map(r => <article key={r.id} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#127373]">{r.status.replaceAll("_", " ")}</p><h2 className="mt-1 text-xl font-bold">{r.appliance?.brand} {r.appliance?.model || r.appliance?.type}</h2><p className="mt-2 text-gray-700">{r.problem}</p>{r.address && <p className="mt-2 flex items-center gap-2 text-sm text-gray-500"><FaMapMarkerAlt />{r.address}</p>}</div><span className="font-mono text-xs text-gray-400">#{r.id.slice(0, 8)}</span></div>{r.status === "DIAGNOSING" && <div className="mt-5 border-t pt-4"><label className="text-sm font-semibold">Diagnosis and recommended work<textarea value={diagnosis[r.id] || ""} onChange={e => setDiagnosis({ ...diagnosis, [r.id]: e.target.value })} className="mt-2 h-24 w-full rounded-lg border border-gray-300 p-3" placeholder="Describe the observed issue and recommended repair…" /></label><button onClick={() => saveDiagnosis(r.id)} className="mt-3 rounded-lg bg-[#127373] px-4 py-2 font-semibold text-white">Save diagnosis</button></div>}{nextActions[r.status] && <div className="mt-5 flex flex-wrap gap-3 border-t pt-4">{nextActions[r.status].map(action => <button key={action} onClick={() => changeStatus(r.id, action)} className="rounded-lg bg-[#112E40] px-4 py-2 text-sm font-semibold text-white">{labels[action]}</button>)}</div>}</article>)}</div>}</div></main>;
}
